### PR TITLE
Naive bayes planner

### PR DESCRIPTION
**Pull request by djlawren**
## Description

These changes introduce a new planner to the repo. This planner selects next action based on highest probability of success, as determined from historical operation report data.

This is a recommit of past PR so that feature branches comes from this repo. Reference old comments here: [https://github.com/mitre/stockpile/pull/560](https://github.com/mitre/stockpile/pull/560)

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Remains to be tested.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by djlawren** [comment]
@elegantmoose Completed my first pass on static refactor. Still remains to be tested, but I am relatively happy with state of code.

Open to further suggestions on cleanup.

**Comment by elegantmoose** [comment]
@djlawren I know we once talked about using a dataframe to the link data. Was that tossed to reduce dependencies? (of say pandas)

**Comment by djlawren** [comment]
> @djlawren I know we once talked about using a dataframe to the link data. Was that tossed to reduce dependencies? (of say pandas)

My recollection is that Kirill's initial version used Pandas prior to a rewrite to remove the dependency.

**Review by elegantmoose — DISMISSED** [review]
tested

**Review by elegantmoose — APPROVED** [review]

**Pull request merged**
